@ContosoBookstore.Api_HostAddress = http://localhost:5089

GET {{ContosoBookstore.Api_HostAddress}}/api/books
Accept: application/json

###

GET {{ContosoBookstore.Api_HostAddress}}/api/authors
Accept: application/json

###

GET {{ContosoBookstore.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{ContosoBookstore.Api_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###
